# List of plugins
#
# prefix + I - to [I]nstall plugins
# prefix + U - to [U]pdate plugins
# prefix + alt + u - to [U]ninstall plugins that are not in the list
#
set -g @plugin 'tmux-plugins/tpm'
# Catpuccin Theme
set -g @plugin 'catppuccin/tmux#v2.1.3' # See https://github.com/catppuccin/tmux/tags for additional tags
set -g @catppuccin_flavor 'mocha' # latte, frappe, macchiato or mocha
## important to have insanely stupid window naming
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_window_text "#W"
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'alexwforsythe/tmux-which-key'
set -g mouse 'on'
set -g @continuum-boot 'on'
set -g @continuum-restore 'on'
# Needs to be last
set -g @plugin 'tmux-plugins/tmux-continuum'

# remap prefix from 'C-b' to 'C-a'
unbind C-b
set-option -g prefix C-a
bind-key C-a send-prefix
# reload config file (change file location to your the tmux.conf you want to use)
bind r source-file ~/.tmux.conf

# Start windows and panes # with 1 (not 0), and renumber on close.
set -g base-index 1
set -g pane-base-index 1
set-option -g renumber-windows on

# Prefix Shift+s will open a command prompt in the status line, asking for a new session name. 
# It will either create a new session with that name or attach to an already existing session by that name.
# These two settings let you create/kill a new session when pressing Prefix S (Shift+s) or Prefix K (Shift+k) respectively:
bind S command-prompt -p "New Session:" "new-session -A -s '%%'"
bind K confirm kill-session

# Styling
set-option -g status-position top

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'
